name: Weekly Run Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '10 3 * * *'


jobs:
  weekly_run:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r Bots/requirements.txt
        pip install --upgrade cohere
        
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Run bot_Twitter.py
      env:  
        API_COHERE_KEY: ${{ secrets.API_COHERE_KEY }}
        API_CONSUMER_KEY_X: ${{ secrets.API_CONSUMER_KEY_X }}
        API_CONSUMER_SECRET_X: ${{ secrets.API_CONSUMER_SECRET_X }}
        API_ACCESS_TOKEN_X: ${{ secrets.API_ACCESS_TOKEN_X }}
        API_ACCESS_TOKEN_SECRET_X: ${{ secrets.API_ACCESS_TOKEN_SECRET_X }}
      run: |
        cd Bots
        python3 bot_Twitter.py

    - name: Commit and push anomalias.html
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "GitHub Actions Bot"
        git pull origin main
        git add TestesMapa/anomalias.html
        git commit --allow-empty -m "ci: Adicionando arquivo anomalias.html gerado automaticamente"
        git push origin main --force
