name: Weekly Run Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'


jobs:
  weekly_run:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r Bots/requirements.txt
        pip install --upgrade cohere

    - name: Run bot_Twitter.py
      run: |
        env:  
          API_COHERE_KEY: ${{ secrets.API_COHERE_KEY }}
          API_CONSUMER_KEY_X: ${{ secrets.API_CONSUMER_KEY_X }}
          API_CONSUMER_SECRET_X: ${{ secrets.API_CONSUMER_SECRET_X }}
          API_ACCESS_TOKEN_X: ${{ secrets.API_ACCESS_TOKEN_X }}
          API_ACCESS_TOKEN_SECRET_X: ${{ secrets.API_ACCESS_TOKEN_SECRET_X }}
        cd Bots
        python bot_Twitter.py

    - name: List files (debug)
      run: ls -R
      
    - name: Commit and push anomalias.html
      if: steps.check_changes.outputs.changes_detected == 'true'
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"
        git pul origin main
        git add TestesMapa/anomalias.html
        git commit -m "ci: Adicionando arquivo anomalias.html gerado automaticamente"
        git push origin main
